# cargo-about configuration. Run `cargo about generate -c
# cargo-about/about.toml -o THIRD_PARTY_LICENSES.md cargo-about/about.hbs`
# after a dep change to refresh the bundled attribution file.
#
# The accepted-licences list mirrors the allow list in `cargo-deny/deny.toml`.

accepted = [
    "AGPL-3.0-only",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "GPL-3.0-or-later",
    "ISC",
    "MIT",
    "NCSA",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
